### PR TITLE
Fixed proxy option

### LINKED ISSUE #811: options.proxy = <url> fails with The "url" argument must be of type string
follow up for https://github.com/octokit/rest.js/issues/770#issuecomment-372369198 by @DoomyTheFroomy

> @gr2m sorry for my late reply, unfortunately it does not work. I'm always getting an error: 
> 
> ```
> TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
>     at Url.parse (url.js:106:11)
>     at urlParse (url.js:100:13)
>     at getRequestAgent (C:\Users\Martin-S\git\vi18n-build\node_modules\@octokit\rest\lib\get-request-agent.js:29:20)
>     at parseOptions (C:\Users\Martin-S\git\vi18n-build\node_modules\@octokit\rest\lib\parse-client-options.js:69:36)
>     at new GitHubApi (C:\Users\Martin-S\git\vi18n-build\node_modules\@octokit\rest\index.js:17:33)
>     at Object.<anonymous> (C:\Users\Martin-S\git\vi18n-build\lib\updates.js:25:16)
>     at Module._compile (module.js:649:30)
>     at Object.Module._extensions..js (module.js:660:10)
>     at Module.load (module.js:561:32)
>     at tryModuleLoad (module.js:501:12)
> ```
> 
> The error is caused, because you are trying to [parse the `baseUrl`](https://github.com/octokit/rest.js/blob/master/lib/get-request-agent.js#L29) which is not part of my option configuration (I'm using standard `api.github.com`). The quick and dirty fix would be if you are using [here](https://github.com/octokit/rest.js/blob/ab9ce1399e2044e2966e88305b2bc6daf477f2dd/lib/parse-client-options.js#L69) `clientDefaults.request.agent = getRequestAgent(options)`  instead of `clientDefaults.request.agent = getRequestAgent(userOptions)`

### PR DESCRIPTION
**Pull request by DoomyTheFroomy**
Based on #770 I have done the changes to make the `proxy` option work as expected. I have also added the `DEFAULTS` to the request agent, so it closes #811 .

### CODE REVIEW

File: lib/parse-client-options.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ function parseOptions (userOptions) {
   /* istanbul ignore else */
 
   if (!process.browser) {
-    clientDefaults.request.agent = getRequestAgent(userOptions)
+    clientDefaults.request.agent = getRequestAgent(defaults(userOptions, DEFAULTS))
```
Comment (gr2m) [inline lib/parse-client-options.js]: I think instead of defaulting here, I would pass two arguments, like this

```
getRequestAgent(clientDefaults.baseUrl, userOptions)
```

Because `options.baseUrl` can get constructed by `.host` etc

**Comment by gr2m** [comment]
thanks a lot for the PR :) I created a test case, could you add it to your PR? I can also do it later if you are busy, I’ve made sure locally that it reproduces the bug

```diff
diff --git a/test/integration/agent-proxy/agent-proxy-test.js b/test/integration/agent-proxy/agent-proxy-test.js
index 48968f9..82bf783 100644
--- a/test/integration/agent-proxy/agent-proxy-test.js
+++ b/test/integration/agent-proxy/agent-proxy-test.js
@@ -6,10 +6,13 @@
  * Released under the MIT license
  */
 
+const urlParse = require('url').parse
+
 const Proxy = require('proxy')
 const HttpProxyAgent = require('http-proxy-agent')
 
-const {getInstance} = require('../../util')
+const {getInstance, loadFixture} = require('../../util')
+const Octokit = require('../../../')
 
 require('../../mocha-node-setup')
 
@@ -54,6 +57,37 @@ describe('client proxy', function () {
       })
   })
 
+  it('options.proxy without options.baseUrl (#811)', () => {
+    let proxyReceivedRequest
+
+    proxy.once('request', function (request) {
+      expect(request.headers.accept, 'application/vnd.github.v3+json')
+      proxyReceivedRequest = true
+    })
+
+    return loadFixture('get-organization')
+
+      .then(options => {
+        const {hostname: host, port, path: pathPrefix} = urlParse(options.url)
+        return new Octokit({
+          protocol: 'http',
+          host,
+          port,
+          pathPrefix,
+          proxy: proxyUrl
+        })
+      })
+
+      .then(github => {
+        return github.orgs.get({org: 'octokit-fixture-org'})
+      })
+
+      .then((response) => {
+        expect(response.data.login).to.equal('octokit-fixture-org')
+        expect(proxyReceivedRequest).to.equal(true)
+      })
+  })
+
   it('options.agent = new HttpProxyAgent(proxyUrl)', () => {
     let proxyReceivedRequest
 ```

**Comment by DoomyTheFroomy** [comment]
@gr2m i will do tomorrow if that is okay for you?

**Comment by gr2m** [comment]
of course, thanks for your help

**Comment by DoomyTheFroomy** [comment]
@gr2m I didn't want to break the API so I have just added the [`baseUrl`](https://github.com/DoomyTheFroomy/rest.js/blob/978eb8d02b0bf2249d2d6c43817126f21ab85dd8/lib/parse-client-options.js#L69) to the userOptions object. Please let me know if you don't like it. 

*Edit*

I don't know what I can do to fix the Travis CI build?

File: lib/parse-client-options.js [hunk 2]
```diff
@@ -66,7 +66,8 @@ function parseOptions (userOptions) {
   /* istanbul ignore else */
 
   if (!process.browser) {
-    clientDefaults.request.agent = getRequestAgent(defaults(userOptions, DEFAULTS))
+    userOptions.baseUrl = clientDefaults.baseUrl
+    clientDefaults.request.agent = getRequestAgent(userOptions)
```
Comment (gr2m) [inline lib/parse-client-options.js]: I would prefer

```js
clientDefaults.request.agent = getRequestAgent(clientDefaults.baseUrl , userOptions)
 ```

So we don’t mutate the options object passed in by the user. It requires a change in `get-request-agent.js` but this is not a public API so it’s no problem to change.

Thanks for your help!

**Comment by gr2m** [comment]
> I don't know what I can do to fix the Travis CI build?

The build error was unrelated, it occurred when trying to upload the coverage to coveralls.io. I’m restarting the job

**Update**: restart fixed it :)

**Comment by DoomyTheFroomy** [comment]
@gr2m done 😃

**Review by gr2m — APPROVED** [review]
Thanks a lot 👍
