### PR TITLE
Fix date parsing

### LINKED ISSUE #716: since parameter incorrectly formatted
I've been having a bug with requesting notifications while setting a `since` parameter. The following would not return a notification which came in at `2018-01-22T15:27:32Z`
```js
 octokit.activity.getNotifications({since: '2018-01-21T23:27:32Z' })
```
Upon researching, I found that this was the request getting sent to github 
> https://api.github.com/notifications?since=Mon%20Jan%2022%202018%2007%3A27%3A31%20GMT%2B0800%20(WITA)
>
> This corresponds to 2018-01-22

I don't think this is the correct format, [their api](https://developer.github.com/v3/activity/notifications/#list-your-notifications) expects an ISO string in the format `YYYY-MM-DDTHH:MM:SSZ`.

AFAICT, the error comes from [here](https://github.com/octokit/rest.js/blob/master/lib/plugins/endpoint-methods/validate.js#L59) and [here](https://github.com/octokit/rest.js/blob/master/lib/endpoint/add-query-parameters.js#L19).

The root of the problem is that the value this expression changes based on your system clock.
```js
encodeURIComponent(new Date('2018-01-21T23:27:31.000Z'))
```

I don't think the validate.js should cast dates strings to date objects. I think what it should do instead is try making a date object, and if that fails throw a `new errors.BadRequest` like other validations steps. If it succeeds, it should leave the datestring alone so it is passed to github. 

All this sound okay? I can make a PR for it

### PR DESCRIPTION
**Pull request by JuanCaicedo**
fixes #716

### CODE REVIEW

File: test/integration/params-validations-test.js [hunk 1]
```diff
@@ -127,4 +127,22 @@ describe('params validations', () => {
       due_on: new Date('2012-10-09T23:39:01Z')
     })
   })
+
+  it.skip('Date is passed in correct format for notifications', () => {
```
Comment (JuanCaicedo) [inline test/integration/params-validations-test.js]: I wasn't able to get the test suite to pass, so I figured I would add the tests, then get some feedback and figure out where to put it

File: test/integration/params-validations-test.js [hunk 2]
```diff
@@ -127,4 +127,22 @@ describe('params validations', () => {
...
+    const github = new GitHub()
+
+    nock('https://api.github.com/notifications')
```
Comment (JuanCaicedo) [inline test/integration/params-validations-test.js]: Adding this mock causes other tests to fail. However, it doesn't seem like the changes should happen in [octokit/fixtures](https://github.com/octokit/fixtures) since we need to inspect the query parameter as part of the test. 

I'm not too familiar with nock to know why this is causing failures or what the proper mocking should be

File: test/integration/params-validations-test.js (hunk 1 above)
Comment (JuanCaicedo) [reply test/integration/params-validations-test.js]: I added this test here since the bug stems from old code in the validations. I feel like the proper place would be in a file where other activity endpoints are being tested, but I'm not sure where that is

**Comment by JuanCaicedo** [comment]
I've merged master and added another commit to fix the tests I had skipped. This is ready for review 😀

File: test/integration/params-validations-test.js [hunk 3]
```diff
@@ -127,4 +127,24 @@ describe('params validations', () => {
       due_on: new Date('2012-10-09T23:39:01Z')
     })
   })
+
+  it('Date is passed in correct format for notifications', () => {
+    const github = new GitHub({
+      host: 'notifications-test-host.com'
```
Comment (JuanCaicedo) [inline test/integration/params-validations-test.js]: I saw this pattern used elsewhere of setting a host in order to locally mock the http requests. Not sure if this is the preferred technique, but I added it to get the tests working

Comment (gr2m) [reply test/integration/params-validations-test.js]: Thanks 👌 It is to prevent conflicts with [nock](https://github.com/node-nock/nock) mocks from other test files

File: test/integration/params-validations-test.js [hunk 4]
```diff
@@ -127,4 +127,24 @@ describe('params validations', () => {
       due_on: new Date('2012-10-09T23:39:01Z')
     })
   })
+
+  it('Date is passed in correct format for notifications (#716)', () => {
```
Comment (gr2m) [inline test/integration/params-validations-test.js:131]: @JuanCaicedo I added the `(#716)` to the test description so folks can read up on the discussion behind this test

**Review by gr2m — APPROVED** [review]
Looks great :) Thank you 💐
